trigger:
- main

pool:
  vmImage: 'windows-latest'

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '7.x'

- script: dotnet restore
  displayName: 'Restore packages'

- script: dotnet build --no-restore
  displayName: 'Build project'

- script: dotnet test --no-build --verbosity normal
  displayName: 'Run tests'

- script: dotnet publish -c Release -o out
  displayName: 'Publish app'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'out'
    ArtifactName: 'drop'
